//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test132132.iOS {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("test132132.iOS.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }
        
        internal static string CommonTryAgain {
            get {
                return ResourceManager.GetString("CommonTryAgain", resourceCulture);
            }
        }
        
        internal static string CommonOk {
            get {
                return ResourceManager.GetString("CommonOk", resourceCulture);
            }
        }
        
        internal static string CommonNext {
            get {
                return ResourceManager.GetString("CommonNext", resourceCulture);
            }
        }
        
        internal static string CommonSave {
            get {
                return ResourceManager.GetString("CommonSave", resourceCulture);
            }
        }
        
        internal static string CommonDelete {
            get {
                return ResourceManager.GetString("CommonDelete", resourceCulture);
            }
        }
        
        internal static string CommonDone {
            get {
                return ResourceManager.GetString("CommonDone", resourceCulture);
            }
        }
        
        internal static string SubjectsPageTitle {
            get {
                return ResourceManager.GetString("SubjectsPageTitle", resourceCulture);
            }
        }
        
        internal static string SubjectsSearch {
            get {
                return ResourceManager.GetString("SubjectsSearch", resourceCulture);
            }
        }
        
        internal static string SubjectsSummaryTemplate {
            get {
                return ResourceManager.GetString("SubjectsSummaryTemplate", resourceCulture);
            }
        }
        
        internal static string SubjectsNoMatches {
            get {
                return ResourceManager.GetString("SubjectsNoMatches", resourceCulture);
            }
        }
        
        internal static string SubjectsAZ {
            get {
                return ResourceManager.GetString("SubjectsAZ", resourceCulture);
            }
        }
        
        internal static string SubjectsZA {
            get {
                return ResourceManager.GetString("SubjectsZA", resourceCulture);
            }
        }
        
        internal static string SubjectsSmallFirst {
            get {
                return ResourceManager.GetString("SubjectsSmallFirst", resourceCulture);
            }
        }
        
        internal static string SubjectsLargeFirst {
            get {
                return ResourceManager.GetString("SubjectsLargeFirst", resourceCulture);
            }
        }
        
        internal static string SubjectsHowToDisplay {
            get {
                return ResourceManager.GetString("SubjectsHowToDisplay", resourceCulture);
            }
        }
        
        internal static string SubjectsShortTestsTemplate {
            get {
                return ResourceManager.GetString("SubjectsShortTestsTemplate", resourceCulture);
            }
        }
        
        internal static string SubjectsLongTestsTemplate {
            get {
                return ResourceManager.GetString("SubjectsLongTestsTemplate", resourceCulture);
            }
        }
        
        internal static string SubjectsWhatToDisplay {
            get {
                return ResourceManager.GetString("SubjectsWhatToDisplay", resourceCulture);
            }
        }
        
        internal static string TestViewCellTestTemplate {
            get {
                return ResourceManager.GetString("TestViewCellTestTemplate", resourceCulture);
            }
        }
        
        internal static string TestViewCellQuestionTemplate {
            get {
                return ResourceManager.GetString("TestViewCellQuestionTemplate", resourceCulture);
            }
        }
        
        internal static string TestViewCellTimeTemplate {
            get {
                return ResourceManager.GetString("TestViewCellTimeTemplate", resourceCulture);
            }
        }
        
        internal static string QTypeSelectionPageSelectAlert {
            get {
                return ResourceManager.GetString("QTypeSelectionPageSelectAlert", resourceCulture);
            }
        }
        
        internal static string QTypeSelectionPageMultipleChoiceQuestion {
            get {
                return ResourceManager.GetString("QTypeSelectionPageMultipleChoiceQuestion", resourceCulture);
            }
        }
        
        internal static string QTypeSelectionPageMatchingQuestion {
            get {
                return ResourceManager.GetString("QTypeSelectionPageMatchingQuestion", resourceCulture);
            }
        }
        
        internal static string QTypeSelectionPageOpenQuestion {
            get {
                return ResourceManager.GetString("QTypeSelectionPageOpenQuestion", resourceCulture);
            }
        }
        
        internal static string QTypeSelectionPageTitle {
            get {
                return ResourceManager.GetString("QTypeSelectionPageTitle", resourceCulture);
            }
        }
        
        internal static string MainPageTests {
            get {
                return ResourceManager.GetString("MainPageTests", resourceCulture);
            }
        }
        
        internal static string MainPageEditor {
            get {
                return ResourceManager.GetString("MainPageEditor", resourceCulture);
            }
        }
        
        internal static string MainPageProfile {
            get {
                return ResourceManager.GetString("MainPageProfile", resourceCulture);
            }
        }
        
        internal static string EditorTestsPageAdd {
            get {
                return ResourceManager.GetString("EditorTestsPageAdd", resourceCulture);
            }
        }
        
        internal static string EditorTestsPageYourTests {
            get {
                return ResourceManager.GetString("EditorTestsPageYourTests", resourceCulture);
            }
        }
        
        internal static string EditorPageTitlePlaceholder {
            get {
                return ResourceManager.GetString("EditorPageTitlePlaceholder", resourceCulture);
            }
        }
        
        internal static string EditorPageSubjectPickerPlaceholder {
            get {
                return ResourceManager.GetString("EditorPageSubjectPickerPlaceholder", resourceCulture);
            }
        }
        
        internal static string EditorPageTimeLimit {
            get {
                return ResourceManager.GetString("EditorPageTimeLimit", resourceCulture);
            }
        }
        
        internal static string EditorPageTimeMode {
            get {
                return ResourceManager.GetString("EditorPageTimeMode", resourceCulture);
            }
        }
        
        internal static string EditorPageNewQuestion {
            get {
                return ResourceManager.GetString("EditorPageNewQuestion", resourceCulture);
            }
        }
        
        internal static string EditorPageYourQuestions {
            get {
                return ResourceManager.GetString("EditorPageYourQuestions", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageQuestion {
            get {
                return ResourceManager.GetString("MatchingQEditPageQuestion", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageQuestionPlaceholder {
            get {
                return ResourceManager.GetString("MatchingQEditPageQuestionPlaceholder", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPagePoints {
            get {
                return ResourceManager.GetString("MatchingQEditPagePoints", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPagePointsPlaceholder {
            get {
                return ResourceManager.GetString("MatchingQEditPagePointsPlaceholder", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageNumberOfAnswers {
            get {
                return ResourceManager.GetString("MatchingQEditPageNumberOfAnswers", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageFirstPart {
            get {
                return ResourceManager.GetString("MatchingQEditPageFirstPart", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageSecondPart {
            get {
                return ResourceManager.GetString("MatchingQEditPageSecondPart", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageShuffle {
            get {
                return ResourceManager.GetString("MatchingQEditPageShuffle", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageForgotToShuffle {
            get {
                return ResourceManager.GetString("MatchingQEditPageForgotToShuffle", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageInvalidQuestion {
            get {
                return ResourceManager.GetString("MatchingQEditPageInvalidQuestion", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageStartShuffling {
            get {
                return ResourceManager.GetString("MatchingQEditPageStartShuffling", resourceCulture);
            }
        }
        
        internal static string MatchingQEditPageOptionIsUnrecoverable {
            get {
                return ResourceManager.GetString("MatchingQEditPageOptionIsUnrecoverable", resourceCulture);
            }
        }
        
        internal static string MultipleChoiceQEditPageNumberOfVariants {
            get {
                return ResourceManager.GetString("MultipleChoiceQEditPageNumberOfVariants", resourceCulture);
            }
        }
        
        internal static string OpenQEditPageAnswer {
            get {
                return ResourceManager.GetString("OpenQEditPageAnswer", resourceCulture);
            }
        }
        
        internal static string OpenQEditPageYourAnswerHere {
            get {
                return ResourceManager.GetString("OpenQEditPageYourAnswerHere", resourceCulture);
            }
        }
        
        internal static string AuthorizaiontPageSignUp {
            get {
                return ResourceManager.GetString("AuthorizaiontPageSignUp", resourceCulture);
            }
        }
        
        internal static string AuthorizaiontPageLogIn {
            get {
                return ResourceManager.GetString("AuthorizaiontPageLogIn", resourceCulture);
            }
        }
        
        internal static string AuthorizaiontPageAlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("AuthorizaiontPageAlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        internal static string LogInPageEmailOrUsername {
            get {
                return ResourceManager.GetString("LogInPageEmailOrUsername", resourceCulture);
            }
        }
        
        internal static string LogInPagePassword {
            get {
                return ResourceManager.GetString("LogInPagePassword", resourceCulture);
            }
        }
        
        internal static string LogInPageForgotyYourPassword {
            get {
                return ResourceManager.GetString("LogInPageForgotyYourPassword", resourceCulture);
            }
        }
        
        internal static string SignUpPagePhoto {
            get {
                return ResourceManager.GetString("SignUpPagePhoto", resourceCulture);
            }
        }
        
        internal static string SignUpPageYourName {
            get {
                return ResourceManager.GetString("SignUpPageYourName", resourceCulture);
            }
        }
        
        internal static string SignUpPageYourSurname {
            get {
                return ResourceManager.GetString("SignUpPageYourSurname", resourceCulture);
            }
        }
        
        internal static string SignUpPageDateOfBirth {
            get {
                return ResourceManager.GetString("SignUpPageDateOfBirth", resourceCulture);
            }
        }
        
        internal static string SignUpPageUsername {
            get {
                return ResourceManager.GetString("SignUpPageUsername", resourceCulture);
            }
        }
        
        internal static string SignUpPagePassword {
            get {
                return ResourceManager.GetString("SignUpPagePassword", resourceCulture);
            }
        }
        
        internal static string SignUpPageEmail {
            get {
                return ResourceManager.GetString("SignUpPageEmail", resourceCulture);
            }
        }
        
        internal static string SignUpPageEducation {
            get {
                return ResourceManager.GetString("SignUpPageEducation", resourceCulture);
            }
        }
        
        internal static string SignUpPageBSUIR {
            get {
                return ResourceManager.GetString("SignUpPageBSUIR", resourceCulture);
            }
        }
        
        internal static string SignUpPageSignUp {
            get {
                return ResourceManager.GetString("SignUpPageSignUp", resourceCulture);
            }
        }
        
        internal static string SignUpPageInvalidUsername {
            get {
                return ResourceManager.GetString("SignUpPageInvalidUsername", resourceCulture);
            }
        }
        
        internal static string ProfilePageMyProfile {
            get {
                return ResourceManager.GetString("ProfilePageMyProfile", resourceCulture);
            }
        }
        
        internal static string ProfilePageSettings {
            get {
                return ResourceManager.GetString("ProfilePageSettings", resourceCulture);
            }
        }
        
        internal static string ProfilePageSwipeRight {
            get {
                return ResourceManager.GetString("ProfilePageSwipeRight", resourceCulture);
            }
        }
        
        internal static string UserInformationPageInformation {
            get {
                return ResourceManager.GetString("UserInformationPageInformation", resourceCulture);
            }
        }
        
        internal static string UserInformationPageBirthday {
            get {
                return ResourceManager.GetString("UserInformationPageBirthday", resourceCulture);
            }
        }
        
        internal static string UserInformationPageStudiedAt {
            get {
                return ResourceManager.GetString("UserInformationPageStudiedAt", resourceCulture);
            }
        }
        
        internal static string UserInformationPageContacts {
            get {
                return ResourceManager.GetString("UserInformationPageContacts", resourceCulture);
            }
        }
        
        internal static string UserInformationPageCareer {
            get {
                return ResourceManager.GetString("UserInformationPageCareer", resourceCulture);
            }
        }
        
        internal static string UserInformationPageStatistics {
            get {
                return ResourceManager.GetString("UserInformationPageStatistics", resourceCulture);
            }
        }
        
        internal static string UserInformationPageAchievements {
            get {
                return ResourceManager.GetString("UserInformationPageAchievements", resourceCulture);
            }
        }
        
        internal static string UserInformationPageRating {
            get {
                return ResourceManager.GetString("UserInformationPageRating", resourceCulture);
            }
        }
        
        internal static string SettingsPageEmail {
            get {
                return ResourceManager.GetString("SettingsPageEmail", resourceCulture);
            }
        }
        
        internal static string SettingsPagePassword {
            get {
                return ResourceManager.GetString("SettingsPagePassword", resourceCulture);
            }
        }
        
        internal static string SettingsPageUsername {
            get {
                return ResourceManager.GetString("SettingsPageUsername", resourceCulture);
            }
        }
        
        internal static string SettingsPageLightMode {
            get {
                return ResourceManager.GetString("SettingsPageLightMode", resourceCulture);
            }
        }
        
        internal static string SettingsPageDarkMode {
            get {
                return ResourceManager.GetString("SettingsPageDarkMode", resourceCulture);
            }
        }
        
        internal static string SettingsPageAbout {
            get {
                return ResourceManager.GetString("SettingsPageAbout", resourceCulture);
            }
        }
        
        internal static string SettingsPageAskAQuestion {
            get {
                return ResourceManager.GetString("SettingsPageAskAQuestion", resourceCulture);
            }
        }
        
        internal static string SettingsPageLogOut {
            get {
                return ResourceManager.GetString("SettingsPageLogOut", resourceCulture);
            }
        }
        
        internal static string SettingsPageLanguage {
            get {
                return ResourceManager.GetString("SettingsPageLanguage", resourceCulture);
            }
        }
        
        internal static string SettingsPageGeneral {
            get {
                return ResourceManager.GetString("SettingsPageGeneral", resourceCulture);
            }
        }
        
        internal static string SettingsPageAppearence {
            get {
                return ResourceManager.GetString("SettingsPageAppearence", resourceCulture);
            }
        }
        
        internal static string SettingsPageAccount {
            get {
                return ResourceManager.GetString("SettingsPageAccount", resourceCulture);
            }
        }
        
        internal static string ChangeEmailPageTitle {
            get {
                return ResourceManager.GetString("ChangeEmailPageTitle", resourceCulture);
            }
        }
        
        internal static string ChangeEmailPageCurrent {
            get {
                return ResourceManager.GetString("ChangeEmailPageCurrent", resourceCulture);
            }
        }
        
        internal static string ChangeEmailPageNewEmail {
            get {
                return ResourceManager.GetString("ChangeEmailPageNewEmail", resourceCulture);
            }
        }
        
        internal static string ChangeEmailPageInvalidEmail {
            get {
                return ResourceManager.GetString("ChangeEmailPageInvalidEmail", resourceCulture);
            }
        }
        
        internal static string ChangeLanguagePageChooseLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguagePageChooseLanguage", resourceCulture);
            }
        }
        
        internal static string ChangeLanguagePageChanged {
            get {
                return ResourceManager.GetString("ChangeLanguagePageChanged", resourceCulture);
            }
        }
        
        internal static string ChangeLanguagePageReload {
            get {
                return ResourceManager.GetString("ChangeLanguagePageReload", resourceCulture);
            }
        }
        
        internal static string SupportPageText {
            get {
                return ResourceManager.GetString("SupportPageText", resourceCulture);
            }
        }
        
        internal static string OpenQuestionPageAnswerPlaceholder {
            get {
                return ResourceManager.GetString("OpenQuestionPageAnswerPlaceholder", resourceCulture);
            }
        }
        
        internal static string OpenQuestionPageAnswer {
            get {
                return ResourceManager.GetString("OpenQuestionPageAnswer", resourceCulture);
            }
        }
        
        internal static string OpenQuestionPageEmptyEntry {
            get {
                return ResourceManager.GetString("OpenQuestionPageEmptyEntry", resourceCulture);
            }
        }
        
        internal static string OpenQuestionPageEmptyEntryType {
            get {
                return ResourceManager.GetString("OpenQuestionPageEmptyEntryType", resourceCulture);
            }
        }
        
        internal static string TestChoosedPageSolve {
            get {
                return ResourceManager.GetString("TestChoosedPageSolve", resourceCulture);
            }
        }
        
        internal static string RatingPageUser {
            get {
                return ResourceManager.GetString("RatingPageUser", resourceCulture);
            }
        }
    }
}
